### ISSUE TITLE
Mink status box display error

### ISSUE THREAD

**Issue by anne17** [spraakbanken/mink-frontend#139]
Sometimes sub-boxes displaying wanings, errors and Sparv output don't except the boundary of its parent (the status box):

![image (1)](https://github.com/spraakbanken/mink-frontend/assets/1526661/1c3f3b6b-789a-40de-85a9-253036df90ed)

**Comment by arildm** [comment]
It seems that this was caused by long words in the log output. I have fixed the word wrapping in 9365a96 and hope this should resolve the bug! I tested it by temporarily adding a very long word in the HTML template, right after the actual log output.
