### ISSUE TITLE
Not possible to turn off admin mode

### ISSUE THREAD

**Issue by anne17** [spraakbanken/mink-frontend#147]
From the `/user`-route I always seem to get this regardless whether admin mode is activated or not:
![image](https://github.com/spraakbanken/mink-frontend/assets/1526661/21f84399-6130-428f-a113-6c9864c66a9f)

There seems to be no way of turning the admin mode off.

**Comment by arildm** [comment]
I think this is a duplicate of #144 which is fixed but not yet deployed.
