### ISSUE TITLE
Problem with half-logged-out state

### ISSUE THREAD

**Issue by MartinHammarstedt** [spraakbanken/mink-frontend#17]
After not touching the site for a while, you can still make calls to the backend, but the calls to https://sp.spraakbanken.gu.se/auth/jwt will fail. One result is that you can half-create a corpus. The corpus will be created, but the metadata you entered will not be saved since the JWT call will fail.
I don't know how to best solve this. Should you always begin with a call to the JWT service when you know that such a call will be needed later as part of the current task?

**Comment by arildm** [comment]
A bit tricky to test it, but it should be fixed in 8571b50
