### ISSUE TITLE
Hide temp files in export

### ISSUE THREAD

**Issue by arildm** [spraakbanken/mink-frontend#33]

**Comment by arildm** [comment]
Fixed in 3b44679

**Comment by arildm** [comment]
But when this backend issue is closed, we could skip the filtering in frontend: https://github.com/spraakbanken/mink-backend/issues/68

**Comment by anne17** [comment]
Now the backend hides all the korp and cwb related files. Could you please check if this behaviour meets your expectations?

**Comment by arildm** [comment]
I checked the behaviour and removed the filtering in a3ddea1
