### ISSUE TITLE
Upload data limits

### ISSUE THREAD

**Issue by anne17** [spraakbanken/mink-frontend#38]
This is not a real issue but rather some information about backend changes.

When a user uploads data the backend can now respond with status 413 (Payload Too Large) if the uploaded data exceeds the max content length. In this case a `max_content_length` param will be included in the response indicating the content length limit per request (in bytes).

The `/upload_sources` route has two additional limits (which will also cause a 413 when exceeded): a max corpus size (= sum of all uploaded source files) indicated by the `max_corpus_size` param in the response, and a max size per uploaded source file (`max_file_size`).

It looks like the frontend already handles this adequately by telling the user things like "Failed to upload some source files to 'mink-dxh6e6wtff'. Max file size (10.0 MB) exceeded". I don't think any frontend changes are required for now, but maybe this info is useful in the future (e.g. if there are any plans for translating error messages to Swedish).

**Comment by arildm** [comment]
We'll look at the error message in #52. Thanks for testing!
